services:
  node_red_application:
    build: ../
    network_mode: host
    restart: unless-stopped
    volumes:
      - node_red_data:/data
    environment:
      - APP_KEY=test_app_key
      - CONFIG_FP=/opt/doover/app_config.json

volumes:
  node_red_data:
